//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DLL.rc
//
#define IDD_DIALOG_MainView             2000
#define IDC_MainWnd_TAB                 2000
#define IDD_PAGE1                       2001
#define IDC_BUTTON1                     2001
#define IDC_BUTTON_REPLACE_HEAD         2001
#define IDC_BUTTON_HOOKMAIN             2001
#define IDC_BUTTON_OO                   2001
#define IDC_BUTTON_PIC                  2001
#define IDC_BUTTON_SET_HWND             2001
#define IDC_BUTTON_LOADDRIVER           2001
#define IDC_BUTTON_PATCH_CHECK          2001
#define IDC_BUTTON_SET                  2001
#define IDD_PAGE2                       2002
#define IDC_BUTTON_REPLACE_HEAD2        2002
#define IDC_BUTTON_LOADDLL              2002
#define IDC_BUTTON_UNHOOKMAIN           2002
#define IDC_BUTTON_UNHOOK_CHECK         2002
#define IDD_PAGE3                       2003
#define IDC_EDIT_PAGE1                  2003
#define IDC_LIST_NET_REPORT             2003
#define IDD_PAGE4                       2004
#define IDC_EDIT_VALUE                  2004
#define IDD_PAGE5                       2005
#define IDC_BUTTON_CHANGE               2005
#define IDD_PAGE6                       2006
#define IDC_EDIT_ADDRESS                2006
#define IDD_PAGE7                       2007
#define IDC_EDIT_HOOKADDR               2007
#define IDD_PAGE8                       2008
#define IDC_BUTTON_HOOK                 2008
#define IDC_BUTTON_UNHOOK               2009
#define IDC_BUTTON_ADD                  2009
#define IDC_EDIT_SHOWOFFSET             2010
#define IDC_BUTTON_ADDSHOW              2011
#define IDC_EDIT_FILTER                 2012
#define IDC_BUTTON_SUBSHOW              2012
#define IDC_EDIT_PAGE3                  2013
#define IDC_BUTTON2                     2014
#define IDC_BUTTON_UNLOAD               2014
#define IDC_BUTTON_SHOW_INFO            2014
#define IDC_BUTTON_DATA_HOOK            2014
#define IDC_BUTTON_UPDATE               2015
#define IDC_BUTTON_DATA_UNHOOK          2015
#define IDC_BUTTON_UNMALLOC             2016
#define IDC_BUTTON_MALLOC               2017
#define IDC_BUTTON_TEST_MAL             2018
#define IDC_CHECK1                      2019
#define IDC_CHECK_ONLY                  2019
#define IDC_CHECK_WATCH                 2019
#define IDC_CHECK_EAX                   2019
#define IDC_COMBO1                      2020
#define IDC_CHECK_EBX                   2020
#define IDC_BUTTON_HWND                 2021
#define IDC_CHECK_WATCH_RECORD          2021
#define IDC_CHECK_ECX                   2021
#define IDC_BUTTON_MSG                  2022
#define IDC_CHECK_WATCH2                2022
#define IDC_CHECK_EDX                   2022
#define IDC_EDIT_POINTX                 2023
#define IDC_CHECK_WATCH_RECORD2         2023
#define IDC_CHECK_EDI                   2023
#define IDC_EDIT_POINTY                 2024
#define IDC_CHECK_WATCH_TCP             2024
#define IDC_CHECK_ESI                   2024
#define IDC_BUTTON_MESSAGE              2025
#define IDC_CHECK_WATCH_RECORD_TCP      2025
#define IDC_CHECK7                      2025
#define IDC_CHECK_PARA                  2025
#define IDC_BUTTON_HOOK_DIS             2026
#define IDC_BUTTON_HOOK_DIS2            2027
#define IDC_BUTTON_UNHOOKDIS            2027
#define IDC_BUTTON_HOOK_SEND            2027
#define IDC_BUTTON_START                2028
#define IDC_BUTTON_HOOK_SYS             2028
#define IDC_BUTTON_UNHOOK_DIS           2029
#define IDC_COMBO_COMPAREUDP            2030
#define IDC_COMBO_PAGE3                 2031
#define IDC_BUTTON_UNHOOK_SEND          2032
#define IDC_COMBO_PAGE3_SEND            2033
#define IDC_EDIT_HWND                   2034
#define IDC_BUTTON_UNHOOK_SYS           2035
#define IDC_CHECK_ALL                   2036
#define IDC_COMBO_PAGE8_COMMAND         2036
#define IDC_EDIT_HWND_MINUDP            2036
#define IDC_EDIT1                       2037
#define IDC_EDIT_PAGE7_INFO             2037
#define IDC_EDIT_SPECIAL_CODE           2037
#define IDC_EDIT_HWND_MINTCP            2037
#define IDC_EDIT_KEY                    2038
#define IDC_COMBO_COMPARETCP            2038
#define IDC_BUTTON_ANJIAN               2039
#define IDC_BUTTON_CLEAR                2041
#define IDC_BUTTON_FUNCTION_NAME        2041
#define IDC_EDIT_LUA                    2042
#define IDC_BUTTON_WATCH_SYS            2042
#define IDC_BUTTON_LUA                  2043
#define IDC_BUTTON_UNWATCH_SYS          2043
#define IDC_BUTTON_LUA_EXECUTE          2044
#define IDC_BUTTON_CALLFUNCTION_TEST    2044
#define IDC_EDIT_LUA_PATH               2045
#define IDC_BUTTON_SETWATCH             2045
#define IDC_RADIO1                      2046
#define IDC_EDIT_PAGE4                  2046
#define IDC_RADIO2                      2047
#define IDC_RADIO3                      2048
#define IDC_LIST_PAGE3                  2048
#define IDC_RADIO4                      2049
#define IDC_BUTTON3                     2049
#define IDC_RADIO5                      2050
#define IDC_BUTTON4                     2050
#define IDC_RADIO6                      2051
#define IDC_BUTTON_CANCLEALL            2051
#define IDC_BUTTON_LOLHOOK              2052
#define IDC_EDIT_MODULE                 2053
#define IDC_BUTTON6                     2054
#define IDC_EDIT_SCOPE                  2055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2009
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2056
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
